#!/bin/sh

REPOS="${1}"
TOHOMEPAGE=${DOCDIR}/to_homepage.psv

TMPDIR=`mktemp -d -t uzsolt.hu`

for f in `${SVNLOOK} changed "${REPOS}" | awk '{print $2}'`; do
  # remove trunk/ from filename
  f=${f#*/}
  if grep -q "${f}|" "${TOHOMEPAGE}"; then

    cd ${TMPDIR}
    cp ${DOCDIR}/${f} ${TMPDIR}
    REV=`${SVNLOOK} youngest "${REPOS}"`
    DATE=`date +'%Y.%m.%d. %H:%M'`
    filename=${f##*/}
    TARGETFILE=${STATICDIR}`grep "${f}|" "${TOHOMEPAGE}" | awk -F "|" '{print $2}'`

    if [ -e "${TARGETFILE}" ]; then

      /home/zsolt/bin/tex-convert-homepage "${filename}" \
        "${DATE}" "${REV}"
      ${LATEXMK} -silent -cd -pdf ${TMPDIR}/${filename}
      ${SVNLOOK} info "${REPOS}" | sed "1,3 d" > ${TMPDIR}/commit-msg
      printf "docs/r%s\n" "${REV}" >> ${TMPDIR}/commit-msg
      cp ${filename%.*}.pdf ${TARGETFILE}
      ${SVN} commit ${TARGETFILE} -F ${TMPDIR}/commit-msg
      ${SSH} uzsolt.hu ${SVN} up /home/zsolt/svn/uzsolt.hu

    fi

  fi
done
rm -rf ${TMPDIR}
