#!/bin/sh

set -e
trap "clean" INT TERM EXIT

REPOS="${1}"

for prg in svn svnlook svnmucc; do
  if which -s ${prg}; then
    eval ${prg}=${prg}
  else
    eval ${prg}=/usr/bin/svnlite${prg#svn}
  fi
done

FILES_TO_CLEAN=""

clean() {
  [ -n "${FILES_TO_CLEAN}" ] && rm -r ${FILES_TO_CLEAN}
}

add_svn_ignore() {

  SEXT=tex
  DEXT=pdf
  TMPFILE=`mktemp -t svndocs`
  FILELIST=`mktemp -t svndocs`
  PROPS=`mktemp -t svndocs`
  NEWFILES=`mktemp -t svndocs`
  FILES_TO_CLEAN="${FILES_TO_CLEAN} ${TMPFILE} ${FILELIST} ${PROPS} ${NEWFILES}"

  LASTREV=`${svnlook} youngest ${REPOS}`
  ! ${svnlook} changed ${REPOS} | sed -n "/\.${SEXT}$/ s,^. *,,p" | sort -u > ${TMPFILE}

  for dir in `sed "s,\(.*\)/.*\.${SEXT}$,\1,p" ${TMPFILE} | sort -u`; do

    sed -n "\@^${dir}@ s,${dir}/\(.*\)\.${SEXT},\1.${DEXT},p" ${TMPFILE} > ${FILELIST}
    ! ${svn} propget svn:ignore file://${REPOS}/${dir} | grep -v '^$' | sort -u > ${PROPS}
    comm -23 ${FILELIST} ${PROPS} > ${NEWFILES}

    if [ `stat -f %z ${NEWFILES}` -gt 1 ]; then
      cat ${NEWFILES} ${PROPS} | sort -u > ${FILELIST}
      ${svnmucc} -U file://${REPOS} -m "kihagyás: r${LASTREV}" propsetf svn:ignore ${FILELIST} ${dir}
    fi

  done

}

uzsolt_hu_commit() {

  LATEXMK=/usr/local/bin/latexmk

  DOCDIR=/home/zsolt/docs
  TOHOMEPAGE=${DOCDIR}/to_homepage.psv
  STATICDIR=/home/zsolt/svn/uzsolt.hu/static
  HOST="uzsolt.hu"

  TMPDIR=`mktemp -d -t uzsolt.hu`
  FILES_TO_CLEAN="${FILES_TO_CLEAN} ${TMPDIR}"

  ! ${svnlook} info "${REPOS}" | sed "1,3 d" > ${TMPDIR}/commit-msg
  DATE=`date +'%Y.%m.%d. %H:%M'`
  REV=`${svnlook} youngest "${REPOS}"`
  printf "docs/r%s\n" "${REV}" >> ${TMPDIR}/commit-msg

  TARGETFILES=""
  for f in `! { 
      ${svnlook} changed /home/storage/svn/dokumentumok/ | sed 's,^. * trunk/,,' ;
      awk -F '|' '{print $1}' ${TOHOMEPAGE} ;
    } | sort | uniq -d`; do

    TARGETFILE=${STATICDIR}/`grep "${f}|" "${TOHOMEPAGE}" | awk -F "|" '{print $2}'`
    TARGETFILES="${TARGETFILES} ${TARGETFILE}"
    TEXINPUTS=".:/home/zsolt/texmf/"


    TMPFILE=`mktemp ${DOCDIR}/${f}-XXXX`
    FILES_TO_CLEAN="${FILES_TO_CLEAN} ${TMPFILE}"

    cp ${DOCDIR}/${f} ${TMPFILE}
    JOBNAME="svn-updating-$$"
    /home/zsolt/bin/tex-convert-homepage \
      "${TMPFILE}" "${DATE}" "${REV}"
    ${LATEXMK} -silent -cd --jobname="${JOBNAME}" -pdf "${TMPFILE}"
    cp ${DOCDIR}/${f%/*}/${JOBNAME}.pdf ${TARGETFILE}
    ${LATEXMK} -silent -cd --jobname="${JOBNAME}" -C "${TMPFILE}"

  done

  if [ -n "${TARGETFILES}" ]; then
    ${svn} commit ${TARGETFILES} -F ${TMPDIR}/commit-msg
    ssh ${HOST} svn up /home/zsolt/svn/uzsolt.hu
  fi

}

add_svn_ignore
uzsolt_hu_commit
