#!/bin/sh

# Checkouted repository
REPO_CO=/home/zsolt/svn/svnadmin/
REPO="${1}"

SVNLOOK=/usr/bin/svnlitelook

CHANGED=`${SVNLOOK} changed ${REPO} | awk '/^[^D]/ {print $2}'`
DELETED=`${SVNLOOK} changed ${REPO} | awk '/^D/ {print $2}'`

# $1: server name
get_svn_root() {
  case "$1" in
    localhost)
      echo "/home/storage/svn/"
      ;;
    svn@svn.uzsolt.hu)
      echo "/usr/local/subversion/"
      ;;
  esac
}

# $1: function to run
# $*: the values
for_all() {
  FUNC=$1
  shift
  for i in $*; do
    DESTURL=`echo ${i} | sed "s@/.*@@"`
    FILE=${i} #`echo ${i} | sed "s@^[^/]*/@@"`
    SERVERDIR="${DESTURL}:`get_svn_root ${DESTURL}`"
    ${FUNC} "${SERVERDIR}" "${FILE}"
  done
}

# $1: desturl, "server:directory" format
# $2: file with path relative to svn repository's root
func_scp() {
  scp "${REPO_CO}/${2}" "${1}/${2#*/}"
}

func_rm() {
  ssh "${1%:*}" rm "${1#*:}/${2}"
}

for_all func_scp ${CHANGED}
for_all func_rm ${DELETED}

